[build]
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF docs/"
base = "docs/"
publish = "dist"
command = "yarn deploy"

[functions]
directory = "functions"

[[redirects]]
from = "/api/*"
to = ".netlify/functions/:splat"
status = 200
