# This is a basic workflow that is manually triggered

name: Trigger deployment to Netlify

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: deployment
      - run: |
          git config pull.rebase false
          git pull origin master --no-edit
          git push
